In [39]:
import numpy as np
import torch

In [25]:
b = np.array([-1,4,2,-2])

np.heaviside(b,0)

array([0., 1., 1., 0.])

In [42]:
aten = torch.tensor([[11, 12, 13, 14],
                     [21, 22, 23, 24],
                     [31, 32, 33, 34],
                     [41, 42, 43, 44]])

# i = 2
# print(aten[0: , i:(i+1)])
# print(torch.einsum('ab -> ', aten))

B = torch.empty((4,4))

for i in range(aten.shape[0]):
    for j in range(aten.shape[1]):
        B[i,j] = aten[i,j] + 1

print(B)

tensor([[12., 13., 14., 15.],
        [22., 23., 24., 25.],
        [32., 33., 34., 35.],
        [42., 43., 44., 45.]])


In [35]:
def activation(U,W):
    res = torch.empty((U.shape[1],U.shape[1]))

    for i in range(U.shape[1]):
        for j in range(W.shape[1]):
            vec = torch.mul(U[0: , i:(i+1)], W[0: , j:(j+1)]).detach().to(device).numpy()
            res[i,j] = np.prod(np.heaviside(vec, 0))
    
    return(res)

In [38]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

aten = torch.tensor([[11, 12, 13, 14],
                     [21, 22, 23, 24],
                     [31, 32, 33, 34],
                     [41, 42, 43, 44]])

bten = torch.tensor([[1, 1, 3, -4],
                     [2, 3, 0, 0],
                     [3, 0, 0, 3],
                     [4, -1, 0, 4]])

i = 2
j = 3
# p = torch.mul(aten[0: , i:(i+1)], bten[0: , j:(j+1)])
activation(aten,bten)

tensor([[1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.],
        [1., 0., 0., 0.]])

In [34]:
np.prod(p.detach().cpu().numpy())

0

In [50]:
print(aten)
N = aten.shape[0]-1
d = aten.shape[1]-1

print(N, d)
aten[0:d,0:N]

tensor([[11, 12, 13, 14],
        [21, 22, 23, 24],
        [31, 32, 33, 34],
        [41, 42, 43, 44]])
3 3


tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])